#+TITLE: Learn the C Programming Language
#+AUTHOR: Caesar X Insanium

* Learn C

Some Notes on the C programming language. I hope to be able to add more
information as I learn more about coding in C

** Effective C
   :END:
Notes on book 'Effective C: An Introduction to Professional C
Programming. I chose this book over K&R simply because it was cheaper at
the time but had good reviews on Amazon. Also K&R is pretty old.

** Algorithms in C

~I hope to be able to add Notes on Algorithms~ This is a separate
repository.

- future note: I finished the section on data structures but I stop at the algorithms
  section because I had no I idea what in the heck was going on.

** The C Programming Language

I found a cheap copy and am now read to learn C programming in ANSI C.
I will also be doing a project in ANSI C. But it will take some time.

The book seems to be a reference but it also contains exercises. I will be doing
the exercises in order to get back into programming.

* Practical C

Learning using actual projects. 
